services:
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - filepizza
    volumes:
      - redis_data:/data
  filepizza:
    build: .
    image: kern/filepizza:latest
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - REDIS_URL=redis://redis:6379
    networks:
      - filepizza
    depends_on:
      - redis

networks:
  filepizza:
    driver: bridge

volumes:
  redis_data:
