services:
  redis:
    image: redis:latest
    ports:
      - 127.0.0.1:6379:6379
    networks:
      - fileshare
    volumes:
      - redis_data:/data
  fileshare:
    build: .
    image: kern/filepizza:latest
    ports:
      - 0.0.0.0:8822:80
    environment:
      - PORT=80
      - REDIS_URL=redis://redis:6379
      - COTURN_ENABLED=false
    networks:
      - fileshare
    depends_on:
      - redis
    env_file:
      - .env

networks:
  fileshare:
    driver: bridge

volumes:
  redis_data:
